feat: table实现
Levix/simple-table pull request #1
Opened 2022-05-10 14:11 UTC by bushaoqing

改动：

新增table+pagination组件

2022-05-14 09:09 UTC, Levix requested changes
reviewed!

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/SimpleTable.tsx
> +        <div class='table-wrap'>
可以考虑对结构进行拆分，拆为 head 、 body 等。

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/SimpleTable.tsx
>    setup(props: TableProps, { attrs, emit, slots }) {
`attrs, emit, slots` 没有使用到建议移除掉。

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/SimpleTable.tsx
> +    let currentSortKeyMap = reactive({})
这里的排序字段进来起的有意义一些，如 `ASC`

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/types.ts
> +    type: Object,
类型声明要有意义，尽量不要使用类似于 `Object` `any` 这样的字段。 声明建议补全下。

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/Pagination.tsx
> +      if (maxPage.value <= 1) {
建议可以完善注释，是否可以抽离为一个 hook 文件？

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/Pagination.tsx
> +              value={inputValue}
类名尽量有意义一点。

2022-05-14 09:09 UTC, Levix commented on bsq/src/components/Pagination.tsx
> +              onBlur={e => jumpToPage(Number(e.target.value))}
考虑一下监听回车的场景？

2022-05-16 01:55 UTC, bushaoqing commented on bsq/src/components/SimpleTable.tsx
> +        <div class='table-wrap'>
table中的header和body也没啥逻辑，这里先不拆，我将排序逻辑抽成hook了，这里也就没啥逻辑，相当于纯展示了

2022-05-16 01:56 UTC, bushaoqing commented on bsq/src/components/SimpleTable.tsx
>    setup(props: TableProps, { attrs, emit, slots }) {
fixed

2022-05-16 01:56 UTC, bushaoqing commented on bsq/src/components/SimpleTable.tsx
> +    let currentSortKeyMap = reactive({})
fixed

2022-05-16 01:56 UTC, bushaoqing commented on bsq/src/components/types.ts
> +    type: Object,
fixed

2022-05-16 01:57 UTC, bushaoqing commented on bsq/src/components/Pagination.tsx
> +      if (maxPage.value <= 1) {
这里就是分页逻辑，抽离其他的也用不上

2022-05-16 01:57 UTC, bushaoqing commented on bsq/src/components/Pagination.tsx
> +              value={inputValue}
fixed

2022-05-16 01:57 UTC, bushaoqing commented on bsq/src/components/Pagination.tsx
> +              onBlur={e => jumpToPage(Number(e.target.value))}
fixed

2022-05-20 06:20 UTC, merged