wzl_提交代码
Levix/simple-table pull request #2
Opened 2022-05-10 15:42 UTC by ck-wzl

2022年5月10日23点42分

2022-05-14 09:08 UTC, Levix requested changes
reviewed!

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/WuTable.tsx
> +import { type TableProps, tableProps } from "./types";
```suggestion
import type { TableProps, tableProps } from "./types";
```

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/WuTable.tsx
> +    const sortList: any[] = reactive([]);
尽量不要出现 any 的写法，把类型声明补全。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/WuTable.tsx
> +    const { handledColumns } = useColumns(props);
这里建议传具体的属性进去就好了，不用把整个 `props` 传进去。所有的 hook 都可以改进一下。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/WuTable.tsx
> +import { defineComponent, provide, reactive, ref } from "vue";
主体表格命名为 `index.tsx`，通过 `index.ts` 暴露到外部使用。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/WuTable.tsx
> +  setup(props: TableProps, { attrs, emit, slots }) {
`attrs, emit, slots` 没使用到的话就不要引入了。

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useColumns.ts
> +    const handledColumns = computed(() => {
这里的变量命令修改一下，你这里应该是返回列数据？就不要用动词了。

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useColumns.ts
> +        const { columns } = toRefs(props);
这个是不是挪到外部？

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useColumns.ts
> +function handleColumns(columns: TableColumn[]) {
建议都用箭头函数来写吧，现在一些是 function，一些又是 arrow fn，统一一下。

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useColumns.ts
> +    const _align = align ?? "start";
这里的对齐方式建议使用 `left | right | center`。

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useColumns.ts
> +    const _key = key ?? `"WU_TABLE_KEY_"${index}`;
这里建议不要这么写，防止空字符问题。

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useDataSource.ts
> +import { type TableColumn, type TableProps } from "../components/types";
```suggestion
import type { TableColumn, TableProps } from "../components/types";
```

`type` 类型建议统一写到外部，避免每次都写一下。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/types.ts
> +    type: Array as PropType<any[]>,
```suggestion
    type: Array as PropType<Record<string, any>[]>,,
```
这里建议不要将 Vue 的属性混入到这里，将他挪动到对应的文件夹，这里应该只有 TableProps 这样的属性就可以了。

2022-05-14 09:08 UTC, Levix commented on wzl/src/composables/useDataSource.ts
> +    } else if (columns[i].sortable?.orderBy === "descend") {
orderBy 建议使用 `'' | 'asc' | 'desc' | 'ASC' | 'DESC'` 这样来定义。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/WuTable.tsx
> +          width="90%"
`width` 是废弃属性来的，建议不要使用了。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/Head.tsx
> +      emit("changeSort", [key, status.value]);
建议这里定义好 emits 的类型，避免盲盒。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/Head.tsx
> +      emit("changeSort", [key, status.value]);
如
```
emits: {
  changeSort: (params: (number | string)[]) => true,
},
```

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/Body.tsx
> +          sortDataList.data.sort((a, b) => {
排序的方式可以有默认的排序操作，但可以支持传入对应的 sortFn 进来，扩展性更强一点。

2022-05-14 09:08 UTC, Levix commented on wzl/src/components/Foot.tsx
> +      if (page < 1 || page > pageSize.value) {
建议如果没有上、下页了，可以给个禁用态就可以。

2022-05-17 15:13 UTC, WuZL567 commented on wzl/src/components/WuTable.tsx
> +import { type TableProps, tableProps } from "./types";
> fixed

2022-05-17 15:29 UTC, WuZL567 commented on wzl/src/components/WuTable.tsx
> +    const sortList: any[] = reactive([]);
fixed

2022-05-17 16:09 UTC, ck-wzl commented on wzl/src/components/WuTable.tsx
> +    const { handledColumns } = useColumns(props);
fixed

2022-05-17 16:10 UTC, ck-wzl commented on wzl/src/components/WuTable.tsx
> +import { defineComponent, provide, reactive, ref } from "vue";
fixed

2022-05-17 16:10 UTC, WuZL567 commented on wzl/src/components/WuTable.tsx
> +  setup(props: TableProps, { attrs, emit, slots }) {
fixed

2022-05-17 16:15 UTC, ck-wzl commented on wzl/src/composables/useColumns.ts
> +    const handledColumns = computed(() => {
fixed

2022-05-17 16:16 UTC, ck-wzl commented on wzl/src/composables/useColumns.ts
> +        const { columns } = toRefs(props);
fixed

2022-05-17 16:16 UTC, ck-wzl commented on wzl/src/composables/useColumns.ts
> +function handleColumns(columns: TableColumn[]) {
fixed，统一arrow fn

2022-05-17 16:18 UTC, ck-wzl commented on wzl/src/composables/useColumns.ts
> +    const _align = align ?? "start";
fixed

2022-05-17 16:18 UTC, ck-wzl commented on wzl/src/composables/useColumns.ts
> +    const _key = key ?? `"WU_TABLE_KEY_"${index}`;
fixed

2022-05-17 16:19 UTC, WuZL567 commented on wzl/src/composables/useDataSource.ts
> +import { type TableColumn, type TableProps } from "../components/types";
fixed

2022-05-17 16:20 UTC, ck-wzl commented on wzl/src/components/types.ts
> +    type: Array as PropType<any[]>,
fixed

2022-05-17 16:24 UTC, ck-wzl commented on wzl/src/composables/useDataSource.ts
> +    } else if (columns[i].sortable?.orderBy === "descend") {
fixed

2022-05-17 16:25 UTC, WuZL567 commented on wzl/src/components/WuTable.tsx
> +          width="90%"
fixed

2022-05-17 17:18 UTC, ck-wzl commented on wzl/src/components/Foot.tsx
> +      if (page < 1 || page > pageSize.value) {
fixed

2022-05-20 06:19 UTC, merged