feat: add table
Levix/simple-table pull request #5
Opened 2022-05-11 10:01 UTC by Sebneil

2022-05-14 09:08 UTC, Levix requested changes
reviewed!

2022-05-14 09:08 UTC, Levix commented on jc/src/components/types.ts
> +        type: Array,
具体的数组内部类型完善一下。

2022-05-14 09:08 UTC, Levix commented on jc/src/components/simple_table.vue
> +                      :key="index"
`key` 不要使用索引值。

2022-05-14 09:08 UTC, Levix commented on jc/src/components/simple_table.vue
> +                      :style="{width: item.defaultWidth || '180px'}"></colgroup>
建议默认值定义在 `style` 中。

2022-05-14 09:08 UTC, Levix commented on jc/src/components/simple_table.vue
> +import TableBody from "./table_body.vue";
这些 hook 建议抽离到单独的文件夹，`components` 主要放组件相关的文件。

2022-05-14 09:08 UTC, Levix commented on jc/src/components/simple_table.vue
> +import { handleSortData } from "./table_action";
建议也使用 `use` 开头

2022-05-14 09:08 UTC, Levix commented on jc/src/components/simple_table.vue
> +    setup(props, { emit }) {
`emit` 去除

2022-05-14 09:08 UTC, Levix commented on jc/src/components/use_pagination.ts
> +        vm?.emit('page-change', activeNum.value);
这个事件触发在哪里定义的？

2022-05-14 09:08 UTC, Levix commented on jc/src/components/use_pagination.ts
> +    let activeNum: Ref<number> = ref(0);
```suggestion
   let activeNum = ref<number>(0);
```
考虑用这种方式？

2022-05-14 09:08 UTC, Levix commented on jc/src/components/table_action.ts
> +export function handleSortData (showPagination: boolean, pageDataLength: number, activeNum: Ref<number>, sortDirection: Ref<string>, sortIndex: Ref<string>, tableData: Array<Object>) {
这么多参数可以考虑用对象来存？例如 options

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/table_action.ts
> +export function handleSortData (showPagination: boolean, pageDataLength: number, activeNum: Ref<number>, sortDirection: Ref<string>, sortIndex: Ref<string>, tableData: Array<Object>) {
1

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/use_pagination.ts
> +        vm?.emit('page-change', activeNum.value);
1

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/simple_table.vue
> +    setup(props, { emit }) {
1

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/simple_table.vue
> +import { handleSortData } from "./table_action";
1

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/simple_table.vue
> +import TableBody from "./table_body.vue";
1

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/simple_table.vue
> +                      :style="{width: item.defaultWidth || '180px'}"></colgroup>
1

2022-05-19 11:39 UTC, Sebneil commented on jc/src/components/simple_table.vue
> +                      :key="index"
1

2022-05-20 06:20 UTC, merged